### ISSUE TITLE
PHP8 Error finding "uri" property

### ISSUE THREAD

**Issue by toto33331** [notfalsedev/laravel-soap#192]
When I test on PHP8, I have this error `Error finding "uri" property`

**Comment by GonzaloGPF** [comment]
Same problem here. After upgrading to Php 8 I'm facing this issue. Please need a way to solve this!
Thanks!

**Comment by alcaamado** [comment]
Same here.
Could anyone fix the problem with some workaround?

**Comment by toto33331** [comment]
Afin a long time searching for a solution, I find out that there's actually the solution on this repo...
Here ==> #190

**Comment by notfalsedev** [comment]
PR merged in 0.3.0.10

https://github.com/notfalsedev/laravel-soap/releases/tag/0.3.0.10
